//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: global::System.Reflection.AssemblyProductAttribute("MyTutorial1")]
[assembly: global::System.Reflection.AssemblyTitleAttribute("MyTutorial1")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="MyTutorial1.Y2013.M11, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e8e295361" +
    "b27a644")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformMyTutorial1 {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Robotics.MyTutorial1.Proxy.MyTutorial1State), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_MyTutorial1_Proxy_MyTutorial1State_TO_Robotics_MyTutorial1_MyTutorial1State));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Robotics.MyTutorial1.MyTutorial1State), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_MyTutorial1_MyTutorial1State_TO_Robotics_MyTutorial1_Proxy_MyTutorial1State));
        }
        
        private static global::Robotics.MyTutorial1.Proxy.MyTutorial1State _cachedInstance0 = new global::Robotics.MyTutorial1.Proxy.MyTutorial1State();
        
        private static global::Robotics.MyTutorial1.MyTutorial1State _cachedInstance = new global::Robotics.MyTutorial1.MyTutorial1State();
        
        public static object Robotics_MyTutorial1_Proxy_MyTutorial1State_TO_Robotics_MyTutorial1_MyTutorial1State(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object Robotics_MyTutorial1_MyTutorial1State_TO_Robotics_MyTutorial1_Proxy_MyTutorial1State(object transformFrom) {
            return _cachedInstance0;
        }
    }
}
